apiVersion: apps/v1
kind: Deployment
metadata:
  name: consulta-tabelas-api
  namespace: consultatabelas
spec:
  selector:
    matchLabels:
      app: consulta-tabelas-api
  template:
    metadata:
      labels:
        app: consulta-tabelas-api
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
        - name: consulta-tabelas-api
          image: registry.gitlab.com/meganews2/servicos/consultatabelas:envio-inicial
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "150m"
              memory: "100Mi"
            requests:
              cpu: 120m
              memory: 100Mi
          livenessProbe:
            httpGet:
              path: /saude
              port: 80
          readinessProbe:
            httpGet:
              path: /saude
              port: 80
          env:
            - name: CONNSTRING
              value: "postgres://admin:admin@postgres:5432/tabelas"
            - name: CONNHTTP
              value: "https://portalunico.siscomex.gov.br/classif/api/publico/nomenclatura/download/json"
            - name: CRONEXPRESSION
              value: "0 20 * * *"
            - name: TZ
              value: "America/Bahia"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: registry-credentials
