apiVersion: v1
kind: Secret
metadata:
  namespace: consultatabelas
  name: registry-credentials
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIloyOXRaWE56WjNWcGFUcE5aV2RoUjNWcE1qQXlNQT09IgoJCX0sCgkJInJlZ2lzdHJ5LmdpdGxhYi5jb20iOiB7CgkJCSJhdXRoIjogIloyOXRaWE56WjNWcGFUcG5iSEJoZEMxQk5HOUhSMXBTVW5GZlFXdFlYMnMzT0hNMFRnPT0iCgkJfQoJfSwKCSJhbGlhc2VzIjogewoJCSJidWlsZGVyIjogImJ1aWxkeCIKCX0KfQ==