version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: tabelas
    ports:
      - '5432:5432'
    expose:
      - '5432'
