version: '3.8'
services:
  postgresdb:
    container_name: postgres
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: tabelas
      TZ: America/Bahia
    ports:
      - '5432:5432'
    expose:
      - '5432'
  app:
    build: .
    restart: always
    depends_on:
      - postgresdb
    environment:
      CONNSTRING: "postgres://admin:admin@postgres:5432/tabelas"
      CONNHTTP: "http://mockoon:3001/"
#      CONNHTTP: "https://portalunico.siscomex.gov.br/classif/api/publico/nomenclatura/download/json"
    ports:
      - '8080:8080'
      - '9090:9090'
    expose:
      - '8080'
      - '9090'
  mockoon:
    container_name: mockoon
    build:
      context: ./mockoon
      dockerfile: Dockerfile
      args:
        version: 1
    ports:
      - "3001:3001"