# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:

jobs:
  build-and-test:
    runs-on:
      labels:
        - self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Config Swaggo
      run: go install github.com/swaggo/swag/cmd/swag@latest && swag init
      
    - name: Build
      run: CGO_ENABLED=0 go build -v ./...

    - name: Test
      run: go test -v ./...
