name: api-test

on:
  pull_request:
    branches: main
    
jobs:
  build-and-test:
    runs-on:
      labels:
        - self-hosted
    steps:
    - uses: actions/checkout@v3
        
    - name: API Test
      run: docker-compose --file=docker-compose.test.yml up --exit-code-from newman
