name: API Test

on:
  pull_request:
    branches: main
    
jobs:
  test:
    runs-on:
      labels:
        - self-hosted
    steps:
    - uses: actions/checkout@v3
        
    - name: Run Newman test with Compose
      run: docker-compose --file=docker-compose.test.yml up --exit-code-from newman
